### ISSUE TITLE
[Feat] RecentLocation repository

### ISSUE THREAD

**Issue by hyeonji91** [moti-app/moti_Android#12]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- RecentLocation repository 구현

## ✅ To-Do
> 작업 계획 작성
- [x] 검색 기록 추가
- [x] 검색 기록 업데이트
- [x] 검색 기록 삭제
- [x] 최금 검색 10개 조회
- [x] 장소 저장 추가 (10개 제한)
- [x] 저장한 장소 삭제
- [x] 저장한 장소 전체 조회
