### ISSUE TITLE
[Feat] Map and Memo

### ISSUE THREAD

**Issue by bingbingbingsu** [moti-app/moti_Android#13]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- 메모 추가 프래그먼트, 지도 프래그먼트 기능 구현

## ✅ To-Do
> 작업 계획 작성
- [x] 메모 추가 프래그먼트 이벤트 연결
- [x]  메모 추가 프래그먼트 데이터 베이스 연결
- [x] 지오코딩

- [x] 지도 프래그먼트 마커 추가
- [x] Implemented feature to center the map view on selected locations
- [x] 선택 지역 임시 마커 기능
