### ISSUE TITLE
[Feat] MemoFragment 기능 연결 및 UI 수정

### ISSUE THREAD

**Issue by mjeong21** [moti-app/moti_Android#17]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- MemoFragment 기능 연결 및 UI 수정

## ✅ To-Do
> 작업 계획 작성
- [ ] 플러스 버튼 제거
- [ ] 아이템 클릭 시 바텀 시트
- [ ] 메모 DB 연결
