### ISSUE TITLE
[Feat] 바텀 시트 예외 처리

### ISSUE THREAD

**Issue by mjeong21** [moti-app/moti_Android#40]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- 바텀 시트 예외처리

## ✅ To-Do
> 작업 계획 작성
- [x] 제목, 메모가 비어 있으면 비활성화 (버튼 색 비활성화)
- [ ] 제목이 비어있으면 spot으로 뜨도록
- [x] 태그 아이콘 수정
