### ISSUE TITLE
[Feat, Bug] 이미지 관련 작업

### ISSUE THREAD

**Issue by hyeonji91** [moti-app/moti_Android#55]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- 
- 버그 수정
    - 수정 시 이미지 회전
    - 사진 없어도 사진 창이 뜸
- 전체화면 알람에서 사진도 띄워주기

## ✅ To-Do
> 작업 계획 작성
- [x] 수정 시 이미지 회전
- [x] 사진 없어도 사진 창이 뜸
- [x] 전체화면 알람 이미지 추가
    - [ ]  테스트
