### ISSUE TITLE
[Feat] 알림 유형, 바텀 네비 UI 기능 수정

### ISSUE THREAD

**Issue by mjeong21** [moti-app/moti_Android#57]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- 알림 유형, 바텀 네비 UI 기능 수정

## ✅ To-Do
> 작업 계획 작성
- [ ] 알림 유형 UI 수정
- [x] 바텀 네비게이션 UI 수정
- [ ] 메모 눌렀을 때 바텀이 지도로 선택되게
