### ISSUE TITLE
[Bug] 바텀 시트 요일 반복 오류

### ISSUE THREAD

**Issue by mjeong21** [moti-app/moti_Android#61]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- isRepeat가 true이고 값 없을 때도 선택되어 있음
- tagColor toggle 예외처리

## ✅ To-Do
> 작업 계획 작성
- [x] 값이 없을 때 isRepeat 처리
- [x] 값이 없을 때 tagColor toggle 처리
- [x] 선택된 tag를 한 번 더 눌러서 껐을 때 tagColor 처리
