### ISSUE TITLE
[Feat] 알림

### ISSUE THREAD

**Issue by JunH1004** [moti-app/moti_Android#9]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- 데이터 베이스에 알림이 insert, update됨에 따라서 알림이 설정되는 기능 구현

## ✅ To-Do
> 작업 계획 작성
- [x] insert, update 타이밍 체크
- [x] 배너 알림 구현
- [ ] 반복 알림 구현
- [ ] 벗어날 때 알림 구현
- [ ] #33
